name: QuickWhitelist
main: me.gbalint.quickwhitelist.QuickWhitelist
version: ${project.version}
description: Name based whitelist solution
author: gbalint
commands:
  quickwhitelist:
    description: Manage server whitelist with custom features.
    aliases: [qw, qwhitelist, qwl]
permissions:
  quickwhitelist.edit:
    description: Allows editing of the whitelist.
    default: op
  quickwhitelist.add:
    description: Allows adding players to the whitelist using /qw add <player>.
    default: op
  quickwhitelist.remove:
    description: Allows removing players from the whitelist using /qw remove <player>.
    default: op
